import { useState, useEffect, useRef } from 'react';
import * as Device from 'expo-device';
import * as Notifications from 'expo-notifications';
import Constants from 'expo-constants';
import { Platform } from 'react-native';
import { useAuth } from './use-supabase-auth';
import { AuthService } from '@/lib/auth-service';
import { router } from 'expo-router';
import { logError } from '@/lib/error-logger';

// NO top-level Notifications calls here

// appOwnership is 'expo' in Expo Go, null/undefined in production builds
const isExpoGo = Constants.appOwnership === 'expo';

async function registerForPushNotificationsAsync(): Promise<string | null> {
  // Only skip in Expo Go — production APK/IPA should always register
  if (isExpoGo || Platform.OS === 'web') return null;

  try {
    if (!Device.isDevice) {
      console.log('Must use physical device for Push Notifications');
      return null;
    }

    // Step 1 — check permission
    const { status: existingStatus } = await Notifications.getPermissionsAsync();
    let finalStatus = existingStatus;

    // Step 2 — request if not granted
    if (existingStatus !== 'granted') {
      const { status } = await Notifications.requestPermissionsAsync();
      finalStatus = status;
    }

    // Step 3 — bail if denied
    if (finalStatus !== 'granted') {
      console.log('Failed to get push token for push notification!');
      return null;
    }

    // Step 4a — handler (only now, after permission confirmed)
    Notifications.setNotificationHandler({
      handleNotification: async (notification) => {
        const type = notification.request.content.data?.type as string | undefined;
        // Suppress OS push banner for events that already show in-app toasts
        // (escrow status changes and chat messages)
        const isToastCoveredEvent = type
          ? [
              'payment_successful',
              'item_shipped',
              'delivery_confirmed',
              'funds_released',
              'message',
            ].includes(type)
          : false;

        if (isToastCoveredEvent) {
          return {
            shouldShowAlert: false,
            shouldPlaySound: false,
            shouldSetBadge: false,
            shouldShowBanner: false,
            shouldShowList: false,
          };
        }

        return {
          shouldShowAlert: true,
          shouldPlaySound: true,
          shouldSetBadge: false,
          shouldShowBanner: true,
          shouldShowList: true,
        };
      },
    });

    // Step 4b — channel (Android only, after permission)
    if (Platform.OS === 'android') {
      await Notifications.setNotificationChannelAsync('default', {
        name: 'default',
        importance: Notifications.AndroidImportance.MAX,
        vibrationPattern: [0, 250, 250, 250],
        lightColor: '#FF231F7C',
      });
    }

    // Step 4c — get token
    const projectId =
      Constants?.expoConfig?.extra?.eas?.projectId ?? Constants?.easConfig?.projectId;
    if (!projectId) {
      console.error('Missing EAS projectId in app.json extra.eas.projectId');
      return null;
    }
    const tokenData = await Notifications.getExpoPushTokenAsync({ projectId });
    return tokenData.data;
  } catch (error) {
    console.error('Push notification setup failed:', error);
    return null;
  }
}
/**
 * Translates web-style URLs generated by the backend (getNotificationUrl
 * in yrdly-app) to the corresponding mobile route paths in expo-router.
 * Necessary because the web and mobile routing trees differ. Do not
 * remove this thinking it's redundant — the mismatch is real and
 * confirmed (see notification routing audit).
 */
function translateNotificationUrl(url: string): string {
  if (!url || url === '/') return url;

  if (url === '/community') return '/(tabs)/catalog?tab=Discover&mode=circle';
  if (url === '/messages') return '/(tabs)/messages';
  if (url.startsWith('/messages/')) {
    const id = url.split('/')[2];
    return `/chat/${id}`;
  }
  if (url === '/home') return '/(tabs)';
  if (url === '/events') return '/(tabs)/catalog?tab=Events';
  if (url === '/my-tickets') return '/tickets';
  if (url === '/marketplace') return '/(tabs)/catalog?tab=Marketplace';
  if (url.startsWith('/posts/') || url.startsWith('/transactions')) return url;

  logError(`Unrecognized notification URL mapping: ${url}`, { context: 'push-notifications' });
  return url;
}

export function usePushNotifications() {
  const [expoPushToken, setExpoPushToken] = useState('');
  const [notification, setNotification] = useState<Notifications.Notification | false>(false);
  const notificationListener = useRef<Notifications.EventSubscription | null>(null);
  const responseListener = useRef<Notifications.EventSubscription | null>(null);
  const { user } = useAuth();

  useEffect(() => {
    if (!user || isExpoGo || Platform.OS === 'web') return;

    let mounted = true;

    registerForPushNotificationsAsync().then((token) => {
      if (!mounted || !token) return;

      // Save token to your backend/Supabase here
      setExpoPushToken(token);
      AuthService.updateUserProfile(user.id, { push_token: token }).catch(console.error);

      // Step 4d & 4e — listeners, only after successful registration
      notificationListener.current = Notifications.addNotificationReceivedListener((n) => {
        setNotification(n);
      });

      responseListener.current = Notifications.addNotificationResponseReceivedListener(
        (response) => {
          console.log('Notification Response:', response);
          const data = response.notification.request.content.data;
          const url = data?.url;

          if (typeof url === 'string') {
            router.push(translateNotificationUrl(url) as any);
          }
        }
      );
    });

    return () => {
      mounted = false;
      if (notificationListener.current) {
        notificationListener.current.remove();
      }
      if (responseListener.current) {
        responseListener.current.remove();
      }
    };
  }, [user]);

  return { expoPushToken, notification };
}
